version: "3.8"
services:
  pod1:
    build: ./pod1
    ports:
      - "3000:3000"
    image: pod1
  pod2:
    build: ./pod2
    ports:
      - "4000:4000"
    environment:
      - "PORT=4000"
    image: pod2
    